### ISSUE TITLE
Problem adding car

### ISSUE THREAD

**Issue by Fks13** [ElectricSidecar/ElectricSidecar#23] opened 2024-09-25 15:21 UTC
When trying to add Tesla MY 2023 mod made in Germany I’m just ending up back at the page where you can select Europe or North America, but with a message saying “ Failed to extract authentication token”. Been in contact with Featherless himself, so hopefully it’s an easy fix.

**Comment by jverkoey** [comment] 2024-09-25 17:36
Looking into this now! To confirm: you're trying to log in with the Europe / Middle East / Africa region?

**Comment by Fks13** [comment] 2024-09-25 18:11
That’s correct. I live in Norway and the car is made in Berlin, so I try to log in with the Europe option.Fredrik SkjelleMob: 469 30 ***@***.*** sep. 2024 kl. 19:36 skrev Jeff Verkoeyen ***@***.***>:﻿
Looking into this now! To confirm: you're trying to log in with the Europe / Middle East / Africa region?

**Comment by jverkoey** [comment] 2024-09-25 21:25
The reason for this error isn't immediately obvious so I'm submitting a build for TestFlight with some extra error handling so that we can try to get down to the root cause. In the interest of keeping several threads connected together, can we move this discussion over to https://meta.cars.forum/viewtopic.php?t=28 ?

**Comment by electricsidecar-dev** [comment] 2024-09-25 21:28
Closing this issue to move discussion over to https://meta.cars.forum/viewtopic.php?t=28

**Closed** 2024-09-25 21:28 UTC

**Comment by jverkoey** [comment] 2024-09-25 21:30
Importantly I'll need your email address + registered forum name to send you the TestFlight invite.

**Comment by Fks13** [comment] 2024-09-26 11:45
Okay. Hopefully this will work out! Yes, remove the thread. No problemFredrik SkjelleMob: 469 30 ***@***.*** sep. 2024 kl. 23:26 skrev Jeff Verkoeyen ***@***.***>:﻿
The reason for this error isn't immediately obvious so I'm submitting a build for TestFlight with some extra error handling so that we can try to get down to the root cause. In the interest of keeping several threads connected together, can we move this discussion over to https://meta.cars.forum/viewtopic.php?t=28 ?

**Comment by Fks13** [comment] 2024-09-26 11:46
You can use this email ***@***.***)My username I think is fks13 Fredrik SkjelleMob: 469 30 ***@***.*** sep. 2024 kl. 23:31 skrev Jeff Verkoeyen ***@***.***>:﻿
Importantly I'll need your email address + registered forum name to send you the TestFlight invite.

**Comment by jverkoey** [comment] 2024-09-26 14:38
Hi @Fks13 I can't see your email on github unfortunately. Let's chat over in the forums at https://meta.cars.forum/viewtopic.php?t=28
